# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Github Actions dependencies updates config
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
